name: Build & Scan Microservices with Trivy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push microservice images
        run: |
          SERVICES=(
            adservice
            cartservice
            checkoutservice
            currencyservice
            emailservice
            frontend
            loadgenerator
            paymentservice
            productcatalogservice
            recommendationservice
            shippingservice
          )

          for service in "${SERVICES[@]}"; do
            echo "🚧 Building image for $s

